[package]
name    = "ncollide_utils"
version = "0.2.4"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]


description = "2 and 3-dimensional collision detection library in Rust: module for various common and simple geometric and mathematical operations."
documentation = "http://ncollide.org/doc/ncollide"
homepage = "http://ncollide.org"
repository = "https://github.com/sebcrozet/ncollide"
keywords = [ "collision", "geometry", "distance", "ray", "convex" ]
license = "BSD-3-Clause"

[lib]
name = "ncollide_utils"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"
rand = "*"
num = "*"
nalgebra = "*"
ncollide_math = { path = "../ncollide_math", version = "*" }
