[package]
name    = "ncollide_utils"
version = "0.1.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]

[lib]
name = "ncollide_utils"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide_math]
path = "../ncollide_math"
