[workspace]
members = [ "build/ncollide2d", "build/ncollide3d" ] #, "ncollide_testbed2d", "ncollide_testbed3d" ]

[patch.crates-io]
ncollide2d = { path = "./build/ncollide2d" }
ncollide3d = { path = "./build/ncollide3d" }