[package]
name    = "ncollide_pipeline"
version = "0.2.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]

description = "2 and 3-dimensional collision detection library in Rust: module describing the collision detection pipeline (broad phase/narrow phase) of ncollide."
documentation = "http://ncollide.org/doc/ncollide"
homepage = "http://ncollide.org"
repository = "https://github.com/sebcrozet/ncollide"
keywords = [ "collision detection", "contact", "time of impact", "geometry", "distance", "ray cast", "convex", "intersection" ]
license = "BSD-3-Clause"

[lib]
name = "ncollide_pipeline"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"
nalgebra = "*"

[dependencies.ncollide_math]
path = "../ncollide_math"

[dependencies.ncollide_utils]
path = "../ncollide_utils"

[dependencies.ncollide_entities]
path = "../ncollide_entities"

[dependencies.ncollide_queries]
path = "../ncollide_queries"
