[package]
name    = "ncollide-user-guide-hacd"
version = "0.1.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]

[dependencies.kiss3d]
git = "http://github.com/sebcrozet/kiss3d"

[[bin]]
name = "hacd"
path = "./hacd.rs"
